#!/usr/bin/env python3
"""
Report Generator Module
Generate comprehensive HTML and Markdown reports
"""

import json
from datetime import datetime

class ReportGenerator:
    """Generate detailed reconnaissance reports"""
    
    def generate_html(self, data, filename):
        """Generate HTML report"""
        html = f"""<!DOCTYPE html>
<html>
<head>
    <title>ShadowGhost Report - {data['domain']}</title>
    <style>
        body {{ font-family: Arial, sans-serif; margin: 20px; background: #0a0a0a; color: #00ff00; }}
        .container {{ max-width: 1200px; margin: 0 auto; }}
        .header {{ background: linear-gradient(135deg, #1a1a1a, #000000); padding: 20px; border: 1px solid #00ff00; }}
        .section {{ background: #1a1a1a; margin: 20px 0; padding: 20px; border: 1px solid #003300; }}
        .vulnerability {{ background: #330000; border: 1px solid #ff0000; padding: 10px; margin: 10px 0; }}
        .finding {{ background: #001a00; border: 1px solid #00ff00; padding: 10px; margin: 10px 0; }}
        .critical {{ color: #ff0000; }}
        .high {{ color: #ff6600; }}
        .medium {{ color: #ffcc00; }}
        .low {{ color: #66ff66; }}
        table {{ width: 100%; border-collapse: collapse; }}
        th, td {{ border: 1px solid #003300; padding: 8px; text-align: left; }}
        th {{ background: #002200; }}
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>👻 ShadowGhost Reconnaissance Report</h1>
            <p><strong>Target:</strong> {data['target']}</p>
            <p><strong>Domain:</strong> {data['domain']}</p>
            <p><strong>Scan Date:</strong> {data['timestamp']}</p>
            <p><strong>Duration:</strong> {data.get('scan_duration', 0):.2f} seconds</p>
        </div>
        
        <div class="section">
            <h2>🎯 Executive Summary</h2>
            <p>Total Vulnerabilities Found: {len(data.get('vulnerabilities', []))}</p>
            <p>Open Ports: {len(data.get('open_ports', {}))}</p>
            <p>Subdomains Discovered: {len(data.get('subdomains', []))}</p>
            <p>Technologies Detected: {len(data.get('technologies', []))}</p>
        </div>
        
        <div class="section">
            <h2>🔌 Open Ports</h2>
            <table>
                <tr><th>Port</th><th>Service</th><th>Banner</th></tr>
                {''.join(f"<tr><td>{port}</td><td>{info.get('service', 'Unknown')}</td><td>{info.get('banner', 'N/A')}</td></tr>" for port, info in data.get('open_ports', {}).items())}
            </table>
        </div>
        
        <div class="section">
            <h2>🖥️ Technologies Detected</h2>
            <ul>
                {''.join(f"<li>{tech}</li>" for tech in data.get('technologies', []))}
            </ul>
        </div>
        
        <div class="section">
            <h2>⚠️ Vulnerabilities</h2>
            {''.join(f"<div class='vulnerability'><strong>{vuln.get('type', 'Unknown')}</strong><br><span class='critical'>URL: {vuln.get('url', 'N/A')}</span><br>Payload: {vuln.get('payload', 'N/A')}<br>Evidence: {vuln.get('evidence', 'N/A')}</div>" for vuln in data.get('vulnerabilities', []))}
        </div>
        
        <div class="section">
            <h2>🏢 Hosting Information</h2>
            <p><strong>IP:</strong> {data.get('hosting_info', {}).get('ip', 'Unknown')}</p>
            <p><strong>Provider:</strong> {data.get('hosting_info', {}).get('hosting_provider', 'Unknown')}</p>
            <p><strong>CDN:</strong> {data.get('hosting_info', {}).get('cdn', 'Unknown')}</p>
            <p><strong>Server Type:</strong> {data.get('hosting_info', {}).get('server_type', 'Unknown')}</p>
        </div>
        
        <div class="section">
            <h2>📂 Discovered Directories</h2>
            <ul>
                {''.join(f"<li>{dir_info.get('path', '')} (Status: {dir_info.get('status', 'Unknown')})</li>" for dir_info in data.get('directories', []))}
            </ul>
        </div>
        
        <div class="footer" style="margin-top: 40px; padding: 20px; background: #1a1a1a; border: 1px solid #003300;">
            <p style="color: #666;">Report generated by ShadowGhost v1.0</p>
            <p style="color: #666; font-size: 12px;">For educational and authorized testing purposes only</p>
        </div>
    </div>
</body>
</html>"""
        
        with open(filename, 'w') as f:
            f.write(html)
